services:
  frontend:
    container_name: frontend
    image: angular
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - "backend"
    ports:
      - "8181:80"
      - "8443:443"
      
  nginx:
    container_name: nginx
    depends_on:
      - "frontend"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/star_lisnave_pt.crt:/etc/nginx/ssl/meuCertificado.crt:ro
      - ./nginx/star_lisnave_pt.key:/etc/nginx/ssl/meuCertificado.key:ro
      - ./nginx/star_lisnave_pt.crt:/etc/nginx/certs/meuCertificado.crt
      - ./nginx/star_lisnave_pt.key:/etc/nginx/certs/meuCertificado.key
      - ./nginx/star_lisnave_pt.crt:/etc/nginx/ssl/certs/meuCertificado.crt
      - ./nginx/star_lisnave_pt.key:/etc/nginx/ssl/certs/meuCertificado.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html